import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>LinkedIn 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className='text-3xl font-bold'></p>
      </main>


    </div>
  )
}
